### ISSUE TITLE
Clarification on example

### ISSUE THREAD

**Issue by masenocturnal** [Redundancy/go-sync#5]
I'm assuming that I'm not understanding something so please correct me.  
I thought the example for the gosync application in the readme is a basic example of how you would sync 2 files..is that correct ?

> gosync build filenameToPatchTo
> gosync patch filenameToPatchFrom filenameToPatchTo.gosync

Steps to reproduce:
  $ mkdir -p /tmp/foo
  $ mkdir -p /tmp/foo1
  $ dd if=/dev/urandom of=/tmp/foo/blah.txt count=10240 bs=10240
  $ cd /tmp/foo1
  $  gosync build blah.txt 
  $ gosync patch /tmp/foo/blah.txt /tmp/foo1/blah.gosync  

## Results: 
        am@seattle2:/tmp/foo1$ gosync patch /tmp/foo/blah.txt /tmp/foo1/blah.gosync 
        panic: runtime error: index out of range

        goroutine 1 [running]:
        main.Patch(0xc2080b20c0)
                /home/am/go/src/github.com/Redundancy/go-sync/gosync/patch.go:63 +0x1734
        github.com/codegangsta/cli.Command.Run(0x796f70, 0x5, 0x796cf0, 0x1, 0x8204b0, 0x48,      0x847390, 0x1a8, 0x0, 0x0, ...)
                /home/am/go/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc2080368f0, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
                /home/am/go/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
                /home/am/go/src/github.com/Redundancy/go-sync/gosync/main.go:53 +0x278

## Expected Results:
I wasn't sure exactly what it did but I was presuming the files would be identical or they would have a different checksum or gosync diff would produce different outputs. 

I was hoping to use this as a library to compare the differences between two files and possibly create a patch which I could then apply to the older file to make them identical. Would this be the sort of use case for your library ?

Would the functionality in go diff be adequate for this ?

am@seattle2:/tmp/foo1$ gosync diff /tmp/foo/blah.txt blah.gosync 
Blocksize:  8192
Weak hash count: 0
Using 4 cores

Matched:
Comparisons: 104865796
Weak hash hits: 0
Weak hit rate: 0
Strong hash hits: 0
Weak hash error rate: NaN
Total matched bytes: 0
Total matched blocks: 0
Index blocks: 0
Total missing bytes: 0
Time taken: 4.862401859s

1) Can you explain what the weak hash count is ?
2) Why is the missing bytes 0 if foo1/blah.txt is 0 bytes ?

## System: 
(Ubuntu 14.04 ) (go version go1.4.1 linux/amd64)

**Comment by Redundancy** [comment]
There are a few things here that I clearly need to work on (the tools have been a bit of an after-thought to the library). Other than the reminder that this is clearly not production ready, here is one answer though:

(1) Rsync was built with the idea of a very fast hashing function that can hash a rolling window of bytes efficiently. This hash is not super reliable, but it allows you to quickly discard non-possibilities for windows of bytes, and then confirm a real match using a more expensive hash. The Go-sync library is based on the same basic algorithm, but with modules and interfaces and unit tests (the tools probably need some system tests).

as an example, imagine a simple hashing function that adds up the letter values of a 4 character window for the string: aaaabac. This results in the following windows: aaaa, aaab, aaba, abac. aaaa=4, aaab=5, aaba=5, abac=7. Assuming that we're looking for aaba (5), we can discard two possibilities very easily, and then do a better comparison.

**Comment by Redundancy** [comment]
Alright. I've pushed some changes so that I can more easily test them in some other environments.

Firstly, the tool should be a little better about informing you about usage. The code flow of the patch command was also making my head hurt a bit, so I've started the process of cleaning it up a bit, but that will probably take a few goes. I your case, I think the documentation was out of date and you were missing an argument for where to get the original file content data to use to patch.

Something like this is what I've just tested:
`
mkdir /tmp/foo
dd if=/dev/urandom of=/tmp/foo/blah.txt count=10240 bs=10240
./gosync b /tmp/foo/blah.txt
cp /tmp/foo/blah.txt /tmp/foo/blah1.txt
truncate -s 1048576  /tmp/foo/blah1.txt
./gosync p /tmp/foo/blah1.txt /tmp/foo/blah.gosync /tmp/foo/blah.txt
diff -q /tmp/foo/blah1.txt /tmp/foo/blah.txt
`

`
mkdir: cannot create directory ‘/tmp/foo’: File exists
10240+0 records in
10240+0 records out
104857600 bytes (105 MB) copied, 4.51756 s, 23.2 MB/s
Index for 104857600 file generated in 589.339072ms (1.779240593096125e+08 bytes/S)Starting patching process
Output file is /tmp/foo/blah1.txt
Downloaded 103809024 bytes
Total file is 104857600 bytes
`

Now, obviously this is cheating, it has the file right there. However, the point is more to prove that the basic functionality works, and the library has easily replaced "block sources" that would allow you to pre-generate a patch based on knowledge of the diff (and perhaps an MD5 of the expected input) and store that in a patch file compressed. It's something on the radar, and perhaps doing it would help me by generating more interest in the library itself.

Alternatively, the existing http block source *should* basically work, and doesn't require any knowledge of what you're going from (although the data transfer is not compressed at the moment).

I clearly need system level tests for all of this functionality though, so I'll start thinking about that.

**Comment by masenocturnal** [comment]
Awesome! Thank you for this.

I will attempt to pull the code and try and integrate it in the next few days. 
I'm still learning the language it's self so it may take me a little while to 
integrate this into my application and probably to understand how the library 
is meant to be used . From my perspective having a library to do the heavy 
lifting is definitely valuable so if you have the desire to work on the 
library it's self I'll be sure to exercise it :)

I'm currently anticipating transporting over ssh; so haven't looked into the 
http block source that you mentioned earlier but I may be able to adapt it to 
fit the purpose. 
 
Kind regards
mase

**Comment by Redundancy** [comment]
The BlockSourceBase uses an interface called BlockSourceRequester (which HttpBlockSource implements) - assuming that a pull mechanism works it would be the place to start.

I'll close this issue for now, but feel free to make me aware of any issues that I can help with, since this is exactly the sort of use-case that I've been aiming for.
